@extends('layouts.app')
@section('title', __($title ?? 'Records'))
@section('content')
<div class="space-y-6">
 <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 class="text-2xl font-semibold text-[var(--color-foreground)]">{{ __($heading ?? 'Records') }}</h1><p class="mt-1 text-sm text-[var(--color-foreground-muted)]">{{ __($description ?? '') }}</p></div>@if(isset($createRoute) && (!isset($createAllowed) || $createAllowed))<a href="{{ route($createRoute) }}" class="inline-flex items-center justify-center rounded-lg bg-[var(--color-primary)] px-4 py-2.5 text-sm font-medium text-white hover:bg-[var(--color-primary-hover)]">{{ __('Add new') }}</a>@endif</div>
 @if($errors->any())<x-validation-errors class="mb-4" />@endif
 <div class="overflow-hidden rounded-xl border border-[var(--color-border)] bg-[var(--color-surface)]"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-[var(--color-border)] text-sm"><thead class="bg-[var(--color-surface-muted)]"><tr>@foreach($columns as $column)<th class="px-4 py-3 text-start text-xs font-semibold uppercase tracking-wide text-[var(--color-foreground-muted)]">{{ __($column) }}</th>@endforeach<th class="px-4 py-3 text-end text-xs font-semibold uppercase tracking-wide text-[var(--color-foreground-muted)]">{{ __('Actions') }}</th></tr></thead><tbody class="divide-y divide-[var(--color-border)]">@forelse($rows as $row)@php($id=$row['_id'])@php(unset($row['_id']))<tr class="hover:bg-[var(--color-surface-muted)]">@foreach($row as $cell)<td class="whitespace-nowrap px-4 py-3 text-[var(--color-foreground)]">{!! $cell !!}</td>@endforeach<td class="whitespace-nowrap px-4 py-3 text-end"><a href="{{ route($showRoute, $id) }}" class="font-medium text-[var(--color-primary)] hover:underline">{{ __('View') }}</a>@if(isset($editRoute)) <a href="{{ route($editRoute, $id) }}" class="ms-3 font-medium text-[var(--color-primary)] hover:underline">{{ __('Edit') }}</a>@endif@if(isset($deleteRoute))<form action="{{ route($deleteRoute, $id) }}" method="POST" class="ms-3 inline" onsubmit="return confirm('{{ __('Delete this record?') }}')">@csrf @method('DELETE')<button class="font-medium text-[var(--color-danger)] hover:underline">{{ __('Delete') }}</button></form>@endif</td></tr>@empty<tr><td colspan="{{ count($columns)+1 }}" class="px-4 py-12 text-center text-sm text-[var(--color-foreground-muted)]">{{ __('No records found.') }}</td></tr>@endforelse</tbody></table></div></div>
</div>
@endsection
